### ISSUE TITLE
Problem with Android

### ISSUE THREAD

**Issue by nraboy** [rdlauer/nativescript-ionic#1] opened 2016-05-28 17:30 UTC
When I try on iOS it works fine, but on Android I get the following:

<img width="462" alt="screen shot 2016-05-28 at 10 30 09 am" src="https://cloud.githubusercontent.com/assets/983958/15628789/3d000ee8-24bf-11e6-8c72-6ca70ae9b4de.png">

**Comment by rdlauer** [comment] 2016-06-01 18:42
Just added some fixes, thanks for the heads-up! There are still some lingering Android issues though, but nothing that is a show-stopper.

**Comment by nraboy** [comment] 2016-06-17 19:22
Your fixes did not correct the problem.  See the following two screenshots:

<img width="631" alt="screen shot 2016-06-17 at 12 21 05 pm" src="https://cloud.githubusercontent.com/assets/983958/16162102/19cb72ba-3486-11e6-9abf-4aaa9a7ee243.png">
<img width="393" alt="screen shot 2016-06-17 at 12 21 26 pm" src="https://cloud.githubusercontent.com/assets/983958/16162103/19cd4dce-3486-11e6-9a07-8df0e18b5a9a.png">

Looks fine on iOS, but bad on Android.  My XML is as follows:

```
<ActionBar title="Password Manager" class="action-bar-positive"></ActionBar>
<StackLayout>
    <StackLayout class="form">
        <GridLayout columns="*, 70" rows="auto" class="form-item">
            <Label text="light" col="0" class="input-label"></Label>
            <Switch checked="true" class="switch-assertive" col="1"></Switch>
        </GridLayout>

        <StackLayout class="hr"></StackLayout>

        <GridLayout columns="*, 70" rows="auto" class="form-item">
            <Label text="stable" col="0" class="input-label"></Label>
            <Switch checked="true" class="switch-balanced" col="1"></Switch>
        </GridLayout>
    </StackLayout>
</StackLayout>
```

**Comment by rdlauer** [comment] 2016-06-21 18:39
Can you try it with the stock demo app to see how the switch works? It _might_ be a column sizing issue, but I doubt it: `<GridLayout columns="*, 70"`

Here is what the demo app looks like on an Android emulator for me (I notice there is an opacity issue with those switches though...).

![screen shot 2016-06-21 at 1 37 03 pm](https://cloud.githubusercontent.com/assets/1918280/16241886/65b8b188-37b5-11e6-855f-b9a026415a0e.png)

**Comment by rdlauer** [comment] 2016-06-21 18:45
Check that - looks like a difference between the styling of the switch widget between Android 4.4.4 and (at least) 6. If I run the stock app on a v4 emulator I see the same experience. It's an on/off block. Not sure there is anything we can do about this!

**Comment by nraboy** [comment] 2016-06-21 18:49
Are you able to come up with the eot and otf files? I am wondering if the older Android versions just don't support ttf font files.

**Comment by rdlauer** [comment] 2016-06-21 18:54
The switch widget shouldn't be dependent on any font files though.

**Comment by nraboy** [comment] 2016-06-21 18:55
Raise a bug with the NS engineering team?  Seems like a pretty serious issue.

**Comment by rdlauer** [comment] 2016-06-21 19:14
@tjvantoll have you seen this before in action? The switch widget seems to behave completely different in Android 4 vs 5/6.

**Comment by tjvantoll** [comment] 2016-06-21 20:19
@rdlauer: I have not but I don’t have a lot of experience with the switch widget. I’ll give this a shot tomorrow and see if I can recreate the problem. I agree with @nraboy that something seems off here.

**Comment by tjvantoll** [comment] 2016-06-22 13:41
Ok this whole thing is just confusing me. With the default app I see no issues with switches on Android 4.x, 5.x, or 6.x. Here’s the app on my 4.x emulator.

![screen shot 2016-06-22 at 9 31 07 am](https://cloud.githubusercontent.com/assets/544280/16268369/2badfde8-385c-11e6-98b7-b215e88bedb2.png)

But with Nic’s XML I do see the issue on Android 4.x, which... confuses me because it’s basically the same XML. Perhaps we should wait until https://github.com/NativeScript/NativeScript/pull/2310/commits/9ac40a5acba7df8f68778a0107081ba167f64dbe lands in a stable release? I’m so confused right now.

**Comment by nraboy** [comment] 2016-06-22 13:43
I done gone broke it ;-)

**Comment by rdlauer** [comment] 2016-06-22 13:46
@tjvantoll You are looking at the checkboxes, which just uses fonts. Check out the switches section to see what you see on 4/5/6.

**Comment by tjvantoll** [comment] 2016-06-22 13:59
Ah! Ok. Then yes I am seeing this. Looks like the issue is `color` isn’t being applied to the `android.widget.Switch` appropriately on Android 4.x. The `background-color` looks fine. Can you create an issue on the modules repo @rdlauer?

**Comment by rdlauer** [comment] 2016-06-22 16:10
Happy to. Is this the right repo for modules? https://github.com/NativeScript/NativeScript

**Comment by tjvantoll** [comment] 2016-06-22 16:11
Yep 😄

**Comment by rdlauer** [comment] 2016-06-22 16:19
Done: https://github.com/NativeScript/NativeScript/issues/2358

**Comment by rdlauer** [comment] 2016-06-24 18:01
Ok guys, I'm going to close this as I think I've tweaked the CSS enough for the switch widget to be palatable for Android 4 and cleaned up a little for 5/6 + iOS. Here are some screenshots for Android 4, 6, and iOS:

![screen shot 2016-06-24 at 12 54 45 pm](https://cloud.githubusercontent.com/assets/1918280/16346189/a6d70cb6-3a0b-11e6-975a-52c8d9e5ef46.png)

![screen shot 2016-06-24 at 12 57 14 pm](https://cloud.githubusercontent.com/assets/1918280/16346196/adc10478-3a0b-11e6-86fa-1d53af9bde02.png)

![screen shot 2016-06-24 at 12 58 27 pm](https://cloud.githubusercontent.com/assets/1918280/16346199/b2d4a29e-3a0b-11e6-9178-1886691c4b03.png)

**Closed as completed by rdlauer** 2016-06-24 18:01 UTC
